import type React from "react";

export const S = {
  root: {
    display: "flex",
    height: "100vh",
    background: "var(--lm-bg)",
    color: "var(--lm-text)",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    fontSize: 14,
  } as React.CSSProperties,
  sidebar: {
    width: 192,
    flexShrink: 0,
    background: "var(--lm-sidebar)",
    borderRight: "1px solid var(--lm-border)",
    display: "flex",
    flexDirection: "column" as const,
  },
  sidebarLogo: {
    padding: "18px 16px 14px",
    borderBottom: "1px solid var(--lm-border)",
  },
  sidebarLogoName: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--lm-amber)",
    letterSpacing: "-0.3px",
  },
  sidebarLogoSub: {
    fontSize: 10,
    color: "var(--lm-text-muted)",
    marginTop: 2,
  },
  navItem: (active: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "8px 14px",
    borderRadius: 8,
    margin: "2px 8px",
    fontSize: 12.5,
    fontWeight: active ? 600 : 400,
    color: active ? "var(--lm-amber)" : "var(--lm-text-dim)",
    background: active ? "var(--lm-amber-dim)" : "transparent",
    cursor: "pointer",
    transition: "all 0.15s",
    border: "none",
    width: "calc(100% - 16px)",
    textAlign: "left" as const,
    textDecoration: "none",
  }),
  navGroupHeader: (hasActiveChild: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "8px 14px",
    borderRadius: 8,
    margin: "2px 8px",
    fontSize: 12.5,
    fontWeight: hasActiveChild ? 600 : 400,
    color: hasActiveChild ? "var(--lm-amber)" : "var(--lm-text-dim)",
    background: hasActiveChild ? "var(--lm-amber-dim)" : "transparent",
    cursor: "pointer",
    transition: "all 0.15s",
    border: "none",
    width: "calc(100% - 16px)",
    textAlign: "left" as const,
    userSelect: "none" as const,
  }),
  navSubItem: (active: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "6px 14px 6px 32px",
    borderRadius: 8,
    margin: "1px 8px",
    fontSize: 12,
    fontWeight: active ? 600 : 400,
    color: active ? "var(--lm-amber)" : "var(--lm-text-muted)",
    background: active ? "var(--lm-amber-dim)" : "transparent",
    cursor: "pointer",
    transition: "all 0.15s",
    border: "none",
    width: "calc(100% - 16px)",
    textAlign: "left" as const,
    textDecoration: "none",
  }),
  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  topbar: {
    padding: "10px 20px",
    borderBottom: "1px solid var(--lm-border)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    padding: "20px",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 14,
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 14,
  },
  card: {
    background: "var(--lm-card)",
    border: "1px solid var(--lm-border)",
    borderRadius: 12,
    padding: 16,
  },
  cardLabel: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--lm-text)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    marginBottom: 12,
  },
};
