// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go-lamp.autonomous.ai/internal/agent"
	"go-lamp.autonomous.ai/internal/ambient"
	"go-lamp.autonomous.ai/internal/beclient"
	"go-lamp.autonomous.ai/internal/buddy"
	"go-lamp.autonomous.ai/internal/device"
	"go-lamp.autonomous.ai/internal/healthwatch"
	"go-lamp.autonomous.ai/internal/monitor"
	"go-lamp.autonomous.ai/internal/network"
	"go-lamp.autonomous.ai/internal/statusled"
	"go-lamp.autonomous.ai/lib/devicebutton"
	"go-lamp.autonomous.ai/lib/mqtt"
	"go-lamp.autonomous.ai/server/config"
	http7 "go-lamp.autonomous.ai/server/buddy/delivery/http"
	http4 "go-lamp.autonomous.ai/server/device/delivery/gpio"
	http3 "go-lamp.autonomous.ai/server/device/delivery/http"
	"go-lamp.autonomous.ai/server/device/delivery/mqtt"
	"go-lamp.autonomous.ai/server/health/delivery/http"
	http2 "go-lamp.autonomous.ai/server/network/delivery/http"
	http6 "go-lamp.autonomous.ai/server/agent/delivery/http"
	http5 "go-lamp.autonomous.ai/server/sensing/delivery/http"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.ProvideConfig()
	service := network.ProvideService(configConfig)
	bus := monitor.ProvideBus()
	statusledService := statusled.ProvideService()
	agentGateway := agent.ProvideGateway(configConfig, bus, statusledService)
	healthHandler := http.ProvideHealthHandler(configConfig, service, agentGateway)
	client := beclient.ProvideClient(configConfig)
	deviceService := device.ProvideService(configConfig, service, agentGateway, client)
	networkHandler := http2.ProvideNetworkHandler(configConfig, service, deviceService)
	deviceHandler := http3.ProvideDeviceHandler(deviceService, service, configConfig)
	mqttConfig := config.ProvideMQTTConfig(configConfig)
	factory, err := mqtt.ProvideFactory(mqttConfig)
	if err != nil {
		return nil, err
	}
	deviceMQTTHandler := mqtthandler.ProvideDeviceMQTTHandler(configConfig, factory, deviceService, service)
	deviceGPIOHandler := http4.ProvideDeviceGPIOHandler(configConfig, service, agentGateway)
	agentHandler := http6.ProvideAgentHandler(agentGateway, bus, statusledService)
	sensingHandler := http5.ProvideSensingHandler(agentGateway, bus, configConfig, statusledService, agentHandler.IsSleeping)
	deviceButton := devicebutton.ProvideDeviceButtonOptional()
	ambientService := ambient.ProvideService(bus)
	healthwatchService := healthwatch.ProvideService(bus, configConfig, statusledService)
	buddyService, err := buddy.ProvideService()
	if err != nil {
		return nil, err
	}
	buddyHandler := http7.ProvideBuddyHandler(configConfig, buddyService)
	server := ProvideServer(configConfig, healthHandler, networkHandler, deviceHandler, deviceMQTTHandler, deviceGPIOHandler, agentHandler, sensingHandler, buddyHandler, deviceService, agentGateway, service, deviceButton, factory, ambientService, healthwatchService, statusledService)
	return server, nil
}
